data = [
  {
    id: 1,
    name: "roar",
    duration: 270.0,
    username: "arthur",
    score: 729,
    lyrics: [
      { song_id: 1, start: 19.5, duration: 5.2, content: "I used to bite my tongue and hold my breath Scared to rock the boat and make a mess" },
      { song_id: 1, start: 24.7, duration: 5.3, content: "So I sat quietly agreed politely" },
      { song_id: 1, start: 30.0, duration: 5.4, content: "I guess that I forgot I had a choice I let you push me past the breaking point" },
      { song_id: 1, start: 35.4, duration: 11.6, content: "I stood for nothing so I fell for everything" },
      { song_id: 1, start: 47.0, duration: 5.2, content: "You held me down but I got up Already brushing off the dust" },
      { song_id: 1, start: 52.0, duration: 5.6, content: "You hear my voice you hear that sound Like thunder gonna shake your ground" },
      { song_id: 1, start: 57.8, duration: 5.2, content: "You held me down but I got up Get ready cause Ive had enough" },
      { song_id: 1, start: 63.0, duration: 3.0, content: "I see it all I see it now" },
      { song_id: 1, start: 66.0, duration: 4.5, content: "I got the eye of the tiger a fighter" },
      { song_id: 1, start: 70.5, duration: 5.5, content: "dancing through the fire Cause I am a champion" },
      { song_id: 1, start: 76.0, duration: 8.0, content: "and youre gonna hear me roar Louder louder than a lion" },
      { song_id: 1, start: 84.0, duration: 3.0, content: "Cause I am a champion" },
      { song_id: 1, start: 87.0, duration: 16.3, content: "and youre gonna hear me roar Oh oh oh oh oh oh Youre gonna hear me roar" },
      { song_id: 1, start: 103.3, duration: 5.4, content: "Now Im floating like a butterfly Stinging like a bee I earned my stripes" },
      { song_id: 1, start: 108.7, duration: 5.1, content: "I went from zero to my own hero" },
      { song_id: 1, start: 113.8, duration: 5.2, content: "You held me down but I got up Already brushing off the dust" },
      { song_id: 1, start: 119.0, duration: 5.0, content: "You hear my voice your hear that sound Like thunder gonna shake your ground" },
      { song_id: 1, start: 124.0, duration: 5.5, content: "You held me down but I got up Get ready cause Ive had enough" },
      { song_id: 1, start: 129.5, duration: 3.0, content: "I see it all I see it now" },
      { song_id: 1, start: 132.5, duration: 4.5, content: "I got the eye of the tiger a fighter" },
      { song_id: 1, start: 137.0, duration: 5.5, content: "dancing through the fire cause I am a champion" },
      { song_id: 1, start: 142.5, duration: 8.0, content: "and youre gonna hear me roar Louder louder than a lion" },
      { song_id: 1, start: 150.5, duration: 3.0, content: "cause I am a champion" },
      { song_id: 1, start: 153.5, duration: 21.5, content: "and youre gonna hear me roar Oh oh oh oh oh oh Youre gonna hear me roar Oh oh oh oh oh oh" },
      { song_id: 1, start: 175.0, duration: 19.0, content: "Youre gonna hear me roar" },
      { song_id: 1, start: 194.0, duration: 4.5, content: "I got the eye of the tiger a fighter" },
      { song_id: 1, start: 198.5, duration: 5.5, content: "dancing through the fire Cause I am a champion" },
      { song_id: 1, start: 204.0, duration: 8.0, content:  "and youre gonna hear me roar Louder louder than a lion" },
      { song_id: 1, start: 212.0, duration: 3.0, content: "Cause I am a champion" },
      { song_id: 1, start: 215.0, duration: 21.0, content: "and youre gonna hear me roar Oh oh oh oh oh oh Youre gonna hear me roar Oh oh oh oh oh oh" },
      { song_id: 1, start: 236.0, duration: 5.0, content: "Youre gonna hear me roar" }
    ]
  },
  {
    id: 2,
    name: "what a wonderful world",
    duration: 130.59,
    username: "chase",
    score: 555,
    lyrics: [
      { song_id: 2, start: 6.02, duration: 4.7, content: "I see trees of green" },
      { song_id: 2, start: 10.72, duration: 6.78, content: "red roses too I see them bloom" },
      { song_id: 2, start: 17.5, duration: 6.94, content: "for me and you And I think to myself" },
      { song_id: 2, start: 24.44, duration: 8.04, content: "what a wonderful world" },
      { song_id: 2, start: 32.48, duration: 4.54, content: "I see skies of blue" },
      { song_id: 2, start: 37.02, duration: 3.4, content: "and clouds of white" },
      { song_id: 2, start: 40.42, duration: 2.22, content: "The bright blessed day" },
      { song_id: 2, start: 42.64, duration: 3.72, content: "the dark sacred night" },
      { song_id: 2, start: 46.36, duration: 4.92, content: "And I think to myself" },
      { song_id: 2, start: 51.28, duration: 8.09, content: "what a wonderful world" },
      { song_id: 2, start: 59.37, duration: 6.65, content: "The colors of the rainbow so pretty in the sky" },
      { song_id: 2, start: 66.02, duration: 5.78, content: "Are also on the faces of people going by" },
      { song_id: 2, start: 71.8, duration: 8.6, content: "I see friends shaking hands saying how do you do" },
      { song_id: 2, start: 80.4, duration: 5.8, content: "Theyre really saying I love you" },
      { song_id: 2, start: 86.2, duration: 4.42, content: "I hear babies crying" },
      { song_id: 2, start: 90.62, duration: 3.52, content: "I watch them grow" },
      { song_id: 2, start: 94.14, duration: 2.22, content: "Theyll learn much more" },
      { song_id: 2, start: 96.36, duration: 3.08, content: "than Ill ever know" },
      { song_id: 2, start: 99.44, duration: 5.08, content: "And I think to myself" },
      { song_id: 2, start: 104.52, duration: 6.38, content: "what a wonderful world" },
      { song_id: 2, start: 110.9, duration: 7.56, content: "Yes I think to myself" },
      { song_id: 2, start: 118.46, duration: 2.56, content: "what a wonderful world" }
    ]
  },
  {
    id: 3,
    name: "gangsters paradise",
    duration: 256.0,
    username: "arthur",
    score: 205,
    lyrics:
    [
    { song_id: 3, start: 26.48, duration: 2.64, content: "As I walk through the valley of the shadow of death"},
    { song_id: 3, start: 28.92, duration: 3.6, content: "I take a look at my life and realize theres nothing left"},
    { song_id: 3, start: 32.92, duration: 3.0, content: "cause I been blasting and laughing so long that"},
    { song_id: 3, start: 35.64, duration: 2.54, content: "even my momma thinks that my mind is gone"},
    { song_id: 3, start: 38.18, duration: 2.8, content: "But I aint never crossed a man that didnt deserve it"},
    { song_id: 3, start: 40.78, duration: 3.28, content: "Me be treated like a punk You know thats unheard of"},
    { song_id: 3, start: 43.76, duration: 3.24, content: "You better watch out your talkin and where your walkin"},
    { song_id: 3, start: 47.4, duration: 2.68, content: "Or you and your homies might be lined in chalk"},
    { song_id: 3, start: 50.08, duration: 3.04, content: "I really hate to trip but I gotta tho"},
    { song_id: 3, start: 53.12, duration: 3.46, content: "as they cope I see myself in the pistol smoke Fool"},
    { song_id: 3, start: 56.08, duration: 2.8, content: "Im the kinda gee the little homies wanna be like"},
    { song_id: 3, start: 59.28, duration: 3.2, content: "On my knees in the night saying prayers in the street light"},
    { song_id: 3, start: 63.78, duration: 6.07, content: "Weve been spending most our lives livin in a gangsters paradise"},
    { song_id: 3, start: 63.78, duration: 6.07, content: "Weve been spending most our lives livin in a gangsters paradise"},
    { song_id: 3, start: 75.92, duration: 6.0, content: "We keep spending most our lives livin in a gangsters paradise"},
    { song_id: 3, start: 75.92, duration: 6.0, content: "We keep spending most our lives livin in a gangsters paradise"},
    { song_id: 3, start: 86.52, duration: 2.64, content: "Look at the situation they got me facin"},
    { song_id: 3, start: 89.16, duration: 3.12, content: "I cant live a normal life I was raised by the street"},
    { song_id: 3, start: 92.68, duration: 2.32, content: "So I gotta be down with the hood team"},
    { song_id: 3, start: 95.0, duration: 3.34, content: "Too much television watchin got me chasing dreams"},
    { song_id: 3, start: 98.34, duration: 2.96, content: "Im an educated fool with money on my mind"},
    { song_id: 3, start: 101.3, duration: 3.0, content: "Got my ten in my hand and a gleam in my eye"},
    { song_id: 3, start: 104.3, duration: 2.8, content: "Im a locd out gangsta set trippin banger"},
    { song_id: 3, start: 107.1, duration: 3.4, content: "And my homies is down so dont arouse my anger fool"},
    { song_id: 3, start: 110.1, duration: 3.0, content: "Death aint nothing but a heartbeat away"},
    { song_id: 3, start: 113.5, duration: 3.6, content: "Im living life Do or die What can I say"},
    { song_id: 3, start: 117.1, duration: 2.2, content: "Im 23 now But will I live to see 24?"},
    { song_id: 3, start: 119.3, duration: 2.8, content: "The way things is goin I dont know"},
    { song_id: 3, start: 122.1, duration: 5.6, content: "Tell me why are we so blind to see"},
    { song_id: 3, start: 127.7, duration: 6.7, content: "That the ones we hurt are you and me"},
    { song_id: 3, start: 134.4, duration: 6.15, content: "Weve been spending most our lives livin in a gangsters paradise"},
    { song_id: 3, start: 134.4, duration: 6.15, content: "Weve been spending most our lives livin in a gangsters paradise"},
    { song_id: 3, start: 152.5, duration: 6.0, content: "We keep spending most our lives livin in a gangsters paradise"},
    { song_id: 3, start: 152.5, duration: 6.0, content: "We keep spending most our lives livin in a gangsters paradise"},
    { song_id: 3, start: 158.7, duration: 3.1, content: "Power and the money Money and the power"},
    { song_id: 3, start: 161.8, duration: 3.1, content: "Minute after minute Hour after hour"},
    { song_id: 3, start: 164.2, duration: 3.1, content: "Everybodys running but half of them aint living"},
    { song_id: 3, start: 167.1, duration: 3.1, content: "Whats going on in the kitchen but I dont know whats cooking"},
    { song_id: 3, start: 170.4, duration: 3.0, content: "They say I gotta learn but no ones here to teach me"},
    { song_id: 3, start: 173.4, duration: 3.2, content: "If they cant understand it How can they teach me"},
    { song_id: 3, start: 176.6, duration: 2.1, content: "I guess they cant I guess they wont"},
    { song_id: 3, start: 178.7, duration: 3.9, content: "I guess the front Thats how I know my life is outta luck fool"},
    { song_id: 3, start: 182.6, duration: 6.0, content: "Weve been spending most our lives livin in a gangsters paradise"},
    { song_id: 3, start: 182.6, duration: 6.0, content: "Weve been spending most our lives livin in a gangsters paradise"},
    { song_id: 3, start: 200.5, duration: 5.8, content: "We keep spending most our lives livin in a gangsters paradise"},
    { song_id: 3, start: 200.5, duration: 5.8, content: "We keep spending most our lives livin in a gangsters paradise"},
    { song_id: 3, start: 206.3, duration: 5.4, content: "Tell me why are we so blind to see"},
    { song_id: 3, start: 211.7, duration: 6.3, content: "That the ones we hurt are you and me"},
    { song_id: 3, start: 218, duration: 5.8, content: "Tell me why are we so blind to see"},
    { song_id: 3, start: 223.8, duration: 6.02, content: "That the ones we hurt are you and me"}
    ]
  },
  {
    id: 4,
    name: "everlong",
    duration: 250.0,
    username: "harim",
    score: 925,
    lyrics: [
      { song_id: 4, start: 32.02, duration: 2.42, content: "Hello"},
      { song_id: 4, start: 34.44, duration: 4.48, content: "Ive waited here for you"},
      { song_id: 4, start: 38.92, duration: 3.66, content: "everlong"},
      { song_id: 4, start: 42.58, duration: 2.56, content: "Tonight"},
      { song_id: 4, start: 45.14, duration: 4.0, content: "I throw myself into"},
      { song_id: 4, start: 49.14, duration: 14.68, content: "And out of the red Out of her head she sang"},
      { song_id: 4, start: 63.82, duration: 6.94, content: "Come down And waste away with me"},
      { song_id: 4, start: 70.76, duration: 3.6, content: "down with me"},
      { song_id: 4, start: 74.36, duration: 6.86, content: "Slow how You wanted it to be"},
      { song_id: 4, start: 81.22, duration: 7.92, content: "Im over my head Out of her head she sang"},
      { song_id: 4, start: 89.14, duration: 4.18, content: "And I wonder"},
      { song_id: 4, start: 93.32, duration: 4.1, content: "When I sing along with you"},
      { song_id: 4, start: 97.42, duration: 6.1, content: "If everything could ever feel this real forever"},
      { song_id: 4, start: 103.52, duration: 6.04, content: "If anything could ever be this good again"},
      { song_id: 4, start: 109.56, duration: 3.26, content: "The only thing Ill ever ask of you"},
      { song_id: 4, start: 112.82, duration: 16.34, content: "You gotta promise not to stop when I say when she sang"},
      { song_id: 4, start: 129.16, duration: 2.34, content: "Breathe out"},
      { song_id: 4, start: 131.5, duration: 4.42, content: "so I can breathe you in"},
      { song_id: 4, start: 135.92, duration: 3.78, content: "Hold you in"},
      { song_id: 4, start: 139.7, duration: 2.52, content: "And now"},
      { song_id: 4, start: 142.22, duration: 4.44, content: "I know youve always been"},
      { song_id: 4, start: 146.66, duration: 7.78, content: "Out of your head Out of my head I sang"},
      { song_id: 4, start: 154.44, duration: 4.14, content: "And I wonder"},
      { song_id: 4, start: 158.58, duration: 4.2, content: "When I sing along with you"},
      { song_id: 4, start: 162.78, duration: 6.08, content: "If everything could ever feel this real forever"},
      { song_id: 4, start: 168.86, duration: 6.04, content: "If anything could ever be this good again"},
      { song_id: 4, start: 174.9, duration: 3.12, content: "The only thing Ill ever ask of you"},
      { song_id: 4, start: 178.02, duration: 32.18, content: "You gotta promise not to stop when I say when she sang"},
      { song_id: 4, start: 210.2, duration: 4.24, content: "And I wonder"},
      { song_id: 4, start: 214.44, duration: 5.94, content: "If everything could ever feel this real forever"},
      { song_id: 4, start: 220.38, duration: 6.08, content: "If anything could ever be this good again"},
      { song_id: 4, start: 226.46, duration: 3.18, content: "The only thing Ill ever ask of you"},
      { song_id: 4, start: 229.64, duration: 4.18, content: "Youve got to promise not to stop when I say when"}
    ]
  },
  {
    id: 5,
    name: "look at me now",
    duration: 63.00,
    username: "Vicky",
    score: 451,
    lyrics: [
      { song_id: 5, start: 32.02, duration: 3.0, content: "Cause Im feelin like Im runnin And Im feelin like I gotta get away get away get away" },
      { song_id: 5, start: 32.02, duration: 3.3, content: "Better know that I dont and I wont ever stop Cause you know I gotta win everydayday" },
      { song_id: 5, start: 32.02, duration: 3.2, content: "See they really really wanna pop me Just know that you will never flop me" },
      { song_id: 5, start: 32.02, duration: 3.1, content: "And I know that I can be a little cocky You aint never gonna stop me" },
      { song_id: 5, start: 32.02, duration: 2.8, content: "Everytime I come gotta set it Then I gotta go and then I gotta get it" },
      { song_id: 5, start: 32.02, duration: 2.8, content: "Then I gotta blow and then I gotta show that Any little thing that think that he be doin" },
      { song_id: 5, start: 32.02, duration: 1.4, content: "Cause it doesnt matter cause Im gonna dadadada" },
      { song_id: 5, start: 32.02, duration: 3.0, content: "Then Im gonna murder everything and anything A badaboom a badabing I gotta do a lotta things" },
      { song_id: 5, start: 32.02, duration: 3.7, content: "That make it clearer to a couple That I always win and then I gotta get it again And again and then again" },
      { song_id: 5, start: 32.02, duration: 2.9, content: "And I be doin it to death And now I move a little foul better call a ref" },
      { song_id: 5, start: 32.02, duration: 3.3, content: "And everybody know my style And know that Im the best When it come to doing this and I be bangin on my chest" },
      { song_id: 5, start: 32.02, duration: 2.9, content: "And I bang in the East and Im bangin in the West And I come to give you more and I will never give you less" },
      { song_id: 5, start: 32.02, duration: 3.5, content: "You will hear it in the street or you could read it in the press Do you really wanna know whats next lets go" },
      { song_id: 5, start: 32.02, duration: 3.2, content: "See the way we on and then we all up in the race And you know we gotta go Dont try to keep up with the pace" },
      { song_id: 5, start: 32.02, duration: 3.3, content: "And we strugglin and hustlin and sendin in and gettin in And we always gotta do it take it to another place" },
      { song_id: 5, start: 32.02, duration: 3.3, content: "Gotta taste it and I gotta grab it And I gotta cut all through this traffic" },
      { song_id: 5, start: 32.02, duration: 2.9, content: "Just to be at the top of the throne better know I gotta have it" }
    ]
  }
]

data.each do |song|
  Song.create(id: song[:id], name: song[:name], duration: song[:duration], username: song[:username], score: song[:score])

  song[:lyrics].each do |lyric_hash|
    Lyric.create(song_id: lyric_hash[:song_id], start: lyric_hash[:start], duration: lyric_hash[:duration], content: lyric_hash[:content])
  end
end
